# Generated by Django 3.0.3 on 2020-03-23 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=1, null=True)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('cel', models.CharField(blank=True, max_length=15, null=True)),
                ('dep', models.CharField(blank=True, max_length=100, null=True)),
                ('birth', models.CharField(blank=True, max_length=55, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('skype', models.CharField(blank=True, max_length=65, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Created',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Erp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=64, null=True)),
                ('desc', models.CharField(blank=True, max_length=65, null=True)),
                ('empresa', models.CharField(blank=True, max_length=65, null=True)),
                ('created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Created')),
            ],
        ),
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Obs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Created')),
            ],
        ),
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('razaosocial', models.CharField(blank=True, max_length=100, null=True)),
                ('nomefantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=15, null=True)),
                ('ie', models.CharField(blank=True, max_length=55, null=True)),
                ('site', models.CharField(blank=True, max_length=155, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=64, null=True)),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('complemento', models.CharField(blank=True, max_length=155, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=64, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=100, null=True)),
                ('contatos', models.ManyToManyField(blank=True, related_name='orgs', to='core.Cliente')),
                ('created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Created')),
                ('erpe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to='core.Erp')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('modalidade', models.CharField(blank=True, max_length=155, null=True)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Created')),
            ],
        ),
        migrations.CreateModel(
            name='Updated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendedorExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
                ('created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Created')),
                ('updated', models.ManyToManyField(to='core.Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=155, null=True)),
                ('isAdmin', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('valorestimado', models.IntegerField(null=True)),
                ('termometro', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='Aberto', max_length=155)),
                ('mtvperd', models.CharField(blank=True, max_length=155, null=True)),
                ('cmtperd', models.CharField(blank=True, max_length=155, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
                ('created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Created')),
                ('estagio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.Estagio')),
                ('obs', models.ManyToManyField(related_name='tickets', to='core.Obs')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Organizacao')),
                ('produto', models.ManyToManyField(to='core.Produto')),
                ('updated', models.ManyToManyField(to='core.Updated')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Vendedor')),
                ('vendedorext', models.ManyToManyField(blank=True, related_name='leads', to='core.VendedorExt')),
            ],
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, default='Semnome', max_length=65)),
                ('created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Created')),
                ('updated', models.ManyToManyField(to='core.Updated')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='updated',
            field=models.ManyToManyField(to='core.Updated'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='ramo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to='core.Ramo'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='updated',
            field=models.ManyToManyField(to='core.Updated'),
        ),
        migrations.AddField(
            model_name='obs',
            name='updated',
            field=models.ManyToManyField(to='core.Updated'),
        ),
        migrations.AddField(
            model_name='erp',
            name='updated',
            field=models.ManyToManyField(to='core.Updated'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Created'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated',
            field=models.ManyToManyField(to='core.Updated'),
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255, null=True)),
                ('dataini', models.CharField(max_length=64, null=True)),
                ('horaini', models.CharField(max_length=64, null=True)),
                ('datafim', models.CharField(max_length=64, null=True)),
                ('horafim', models.CharField(max_length=64, null=True)),
                ('tipo', models.CharField(max_length=64)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
                ('created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Created')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Organizacao')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.Ticket')),
                ('updated', models.ManyToManyField(to='core.Updated')),
            ],
        ),
    ]
