# Generated by Django 3.0.3 on 2020-02-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=5)),
                ('fone', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('skype', models.CharField(max_length=65)),
                ('termometro', models.CharField(max_length=15)),
            ],
        ),
    ]
