# Generated by Django 3.0.3 on 2020-03-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updated',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
