# Generated by Django 3.0.3 on 2020-03-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_updated_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='feito',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
