# Generated by Django 3.0.3 on 2020-02-04 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200204_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='org',
        ),
    ]
