# Generated by Django 3.0.3 on 2020-02-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cliente_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='cliente',
        ),
    ]
