# Generated by Django 3.0.3 on 2020-03-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_atividade_feito'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ramal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
