# Generated by Django 3.0.3 on 2020-04-01 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_ramal'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Vendedor'),
        ),
    ]
