# Generated by Django 3.0.3 on 2020-02-04 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ticket_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estagio',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='org',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Organizacao',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
