# Generated by Django 3.0.3 on 2020-02-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200204_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='celular',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='contato', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='skype',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='termometro',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
