# Generated by Django 3.0.3 on 2020-04-03 14:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_atividade_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=154)),
                ('file', models.FileField(upload_to=core.models.upload_path)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='file',
            field=models.ManyToManyField(blank=True, related_name='ticket_files', to='core.File'),
        ),
    ]
