# Generated by Django 3.0.3 on 2020-04-07 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200403_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Created'),
        ),
    ]
