# Generated by Django 3.0.3 on 2020-02-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='erp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='nome',
            field=models.CharField(default='org', max_length=100),
            preserve_default=False,
        ),
    ]
