# Generated by Django 3.0.3 on 2020-02-05 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
                ('estagio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Estagio')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Organizacao')),
                ('produto', models.ManyToManyField(to='core.Produto')),
            ],
        ),
    ]
