# Generated by Django 3.0.3 on 2020-02-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200204_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='modalidade',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='termometro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='produto',
            field=models.ManyToManyField(to='core.Produto'),
        ),
    ]
