# Generated by Django 3.0.3 on 2020-02-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200205_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Organizacao'),
        ),
    ]
