# Generated by Django 3.0.3 on 2020-02-06 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cliente_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='valorneg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estagio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.Estagio'),
        ),
    ]
