# Generated by Django 3.0.3 on 2020-02-09 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200206_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='descricao',
            new_name='assunto',
        ),
        migrations.RenameField(
            model_name='atividade',
            old_name='duracao',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='valorneg',
            new_name='valorestimado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='termometro',
        ),
        migrations.RemoveField(
            model_name='organizacao',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='descricao',
        ),
        migrations.AddField(
            model_name='atividade',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Organizacao'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='nomefantasia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='razaosocial',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='rua',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='uf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='obs',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='erp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
