# Generated by Django 3.0.3 on 2020-02-13 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200211_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Created',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Updated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, default='Aberto', max_length=155),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Created'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Updated'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Created'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Updated'),
        ),
    ]
