# Generated by Django 3.0.3 on 2020-02-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200213_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='codigo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
