# Generated by Django 3.0.3 on 2020-02-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_organizacao_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='termometro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
