# Generated by Django 3.0.3 on 2020-02-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200214_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Created'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Updated'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Created'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Updated'),
        ),
        migrations.AddField(
            model_name='produto',
            name='created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Created'),
        ),
        migrations.AddField(
            model_name='produto',
            name='updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Updated'),
        ),
    ]
