# Generated by Django 3.0.3 on 2020-02-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200219_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='data',
        ),
        migrations.AddField(
            model_name='atividade',
            name='datafim',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='dataini',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='horafim',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='horaini',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='cnpj',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='complemento',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='ie',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='site',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='telefone',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
