# Generated by Django 3.0.3 on 2020-02-28 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200227_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.Ticket'),
        ),
    ]
