# Generated by Django 3.0.3 on 2020-02-28 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200227_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='assunto',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Created'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Updated'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='obs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
