# Generated by Django 3.0.3 on 2020-02-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200228_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='modalidade',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
