# Generated by Django 3.0.3 on 2020-03-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200228_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, null=True)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='org',
        ),
        migrations.AddField(
            model_name='organizacao',
            name='contatos',
            field=models.ManyToManyField(related_name='orgs', to='core.Cliente'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='obs',
        ),
        migrations.AddField(
            model_name='ticket',
            name='obs',
            field=models.ManyToManyField(related_name='tickets', to='core.Obs'),
        ),
    ]
