# Generated by Django 3.0.3 on 2020-03-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200301_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Erp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=64, null=True)),
                ('desc', models.CharField(blank=True, max_length=65, null=True)),
                ('empresa', models.CharField(blank=True, max_length=65, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=65, null=True)),
            ],
        ),
    ]
