# Generated by Django 3.0.3 on 2020-03-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_erp_ramo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='ramo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to='core.Ramo'),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='contatos',
            field=models.ManyToManyField(blank=True, null=True, related_name='orgs', to='core.Cliente'),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='erp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to='core.Erp'),
        ),
    ]
