# Generated by Django 3.0.3 on 2020-03-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200301_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacao',
            name='erp',
        ),
        migrations.AddField(
            model_name='organizacao',
            name='erpe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to='core.Erp'),
        ),
    ]
