# Generated by Django 3.0.3 on 2020-03-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200301_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacao',
            name='erpe',
        ),
        migrations.RemoveField(
            model_name='organizacao',
            name='ramo',
        ),
    ]
