# Generated by Django 3.0.3 on 2020-03-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200301_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='tipo',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='celular',
            new_name='cel',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='fone',
            new_name='tel',
        ),
        migrations.AddField(
            model_name='cliente',
            name='birth',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dep',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
