# Generated by Django 3.0.3 on 2020-03-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20200302_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramo',
            name='desc',
            field=models.CharField(blank=True, default='Semnome', max_length=65),
        ),
    ]
