# Generated by Django 3.0.3 on 2020-03-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20200302_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cmtperd',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mtvperd',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
