# Generated by Django 3.0.3 on 2020-03-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200304_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
            ],
        ),
    ]
