# Generated by Django 3.0.3 on 2020-03-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_vendedorext'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='vendedorext',
            field=models.ManyToManyField(blank=True, related_name='leads', to='core.VendedorExt'),
        ),
    ]
